try {
  require('dotenv').config();
} catch (error) {
  // The server normally loads .env before this service is required.
}

const https = require('https');
const { chromium } = require('playwright');
const { renderPlanPdfHtml } = require('./renderPlanPdfHtml');

function hasMapCoordinates(locationData = {}) {
  return Number.isFinite(Number(locationData.latitude)) && Number.isFinite(Number(locationData.longitude));
}

function buildMapboxStaticImageUrl(locationData = {}, style = 'outdoors-v12') {
  const latitude = Number(locationData.latitude);
  const longitude = Number(locationData.longitude);
  const token = process.env.MAPBOX_ACCESS_TOKEN;

  if (!token || !Number.isFinite(latitude) || !Number.isFinite(longitude)) return '';

  const lat = latitude.toFixed(6);
  const lon = longitude.toFixed(6);
  const marker = `pin-l+2f5d3a(${lon},${lat})`;
  const viewport = `${lon},${lat},16`;
  const accessToken = encodeURIComponent(token);

  return `https://api.mapbox.com/styles/v1/mapbox/${style}/static/${marker}/${viewport}/640x520@2x?access_token=${accessToken}`;
}

function fetchBuffer(url, timeoutMs = 8000) {
  return new Promise((resolve, reject) => {
    const request = https.get(url, response => {
      const chunks = [];

      if (response.statusCode < 200 || response.statusCode >= 300) {
        response.resume();
        reject(new Error(`Static map request failed with HTTP ${response.statusCode}`));
        return;
      }

      response.on('data', chunk => chunks.push(chunk));
      response.on('end', () => {
        resolve({
          buffer: Buffer.concat(chunks),
          contentType: response.headers['content-type'] || 'image/png'
        });
      });
    });

    request.setTimeout(timeoutMs, () => {
      request.destroy(new Error('Static map request timed out'));
    });

    request.on('error', reject);
  });
}

async function fetchPropertyMapDataUri(locationData = {}) {
  if (!process.env.MAPBOX_ACCESS_TOKEN || !hasMapCoordinates(locationData)) {
    return {
      dataUri: '',
      attribution: 'Map data © OpenStreetMap contributors, imagery/style © Mapbox',
      error: 'Mapbox token or coordinates unavailable.'
    };
  }

  const styles = ['outdoors-v12', 'streets-v12', 'light-v11'];

  for (const style of styles) {
    const url = buildMapboxStaticImageUrl(locationData, style);
    if (!url) continue;

    try {
      const { buffer, contentType } = await fetchBuffer(url);
      const mimeType = /^image\//.test(contentType) ? contentType.split(';')[0] : 'image/png';
      return {
        dataUri: `data:${mimeType};base64,${buffer.toString('base64')}`,
        attribution: 'Map data © OpenStreetMap contributors, imagery/style © Mapbox',
        style,
        error: ''
      };
    } catch (error) {
      // Try the next Mapbox style before falling back to the PDF placeholder.
    }
  }

  return {
    dataUri: '',
    attribution: 'Map data © OpenStreetMap contributors, imagery/style © Mapbox',
    error: 'Property map unavailable.'
  };
}

async function generatePlanPdf(plan) {
  let browser;

  try {
    const propertyMap = await fetchPropertyMapDataUri(plan?.locationData || {});
    const html = renderPlanPdfHtml(plan, { propertyMap });
    browser = await chromium.launch({ headless: true });
    const page = await browser.newPage();

    await page.setContent(html, {
      waitUntil: 'networkidle'
    });

    return await page.pdf({
      format: 'Letter',
      printBackground: true,
      preferCSSPageSize: true,
      displayHeaderFooter: true,
      headerTemplate: '<span></span>',
      footerTemplate: `
        <div style="width:100%;font-size:8px;color:#6b7568;font-family:Arial,Helvetica,sans-serif;padding:0 0.55in;display:flex;justify-content:space-between;align-items:center;">
          <span>Generated by Zodi-Yuga Permaculture</span>
          <span>zodiyuga.com</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `
    });
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}

module.exports = { generatePlanPdf };
